services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: meteo
      POSTGRES_USER: meteo
      POSTGRES_PASSWORD: meteo
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U meteo -d meteo"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  servicioa-tests:
    build:
      context: ./servicioA
      target: tester        # <-- usa la stage "tester" de servicioA/Dockerfile
    depends_on:
      db:
        condition: service_healthy

  serviciob-tests:
    build:
      context: ./servicioB
      target: tests         # <-- usa la stage "tests" de servicioB/Dockerfile
    depends_on:
      - db
